version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_dockerhub
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: andreacb/backend_dockerhub:latest
    container_name: backend_express
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/proyectofinal1"

volumes:
  mongo_data:
