name: Crear y subir imagen de docker
on:
  push:  
    branches:
      - master  
  workflow_dispatch:  
  
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Construir imagen
        run: docker build -t andreacb/ejemplo2:latest .
      - name: Iniciar sesión en Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Subir imagen
        run: docker push andreacb/ejemplo2:latest

